# Generated by Django 3.2.4 on 2021-06-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telegram',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
