# Generated by Django 3.2.4 on 2021-06-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210630_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('suggestion', models.TextField(max_length=700)),
            ],
        ),
    ]
